development:
  adapter: postgresql
  encoding: utf8
  database: notespace_development
  username: brandon
  host: localhost
  pool: 5
  port: 5432
  
production:
  adapter: postgresql
  encoding: utf8
  database: notespace_development
  username: brandon
  host: localhost
  pool: 5
  port: 5432