# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d6019e64125fe8070f8a5af96614df07cdeaa425b700bafb5e741b038d5f2fbe43c1cb35c3eeae8a570b1aff7ea3ea52a973d11a8b772c08dfeab08cbff362a

test:
  secret_key_base: c4f4f31654f95268ee7e94b78ecff6375c4955539296cece01a0744e9b54d32d3b27b1ec4fecfa26430b4990dea062160ebe3314bb5fc376849067ef4de6e340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
